### ISSUE TITLE
TLS Certificate Expired

### ISSUE THREAD

**Issue by NULLx76** [felixgravila/fseconomy-plot-missions#13]
Just wanted to let you know that the TLS certificate for the website has expired:
![image](https://user-images.githubusercontent.com/1809198/93001793-dee56680-f531-11ea-8876-9f451cd8a2f6.png)

**Comment by felixgravila** [comment]
Thank you for letting me know. Seems certbot has been doing some weird stuff and now I can't create a new certificate for a while since too many were already issued. I'll try to fix this asap as soon as it lets me.

**Comment by NULLx76** [comment]
I've thrown up a mirror using github pages: https://nullx76.github.io/fseconomy-plot-missions/ might be worth considering, it's very low maintenance.

**Comment by felixgravila** [comment]
Thanks for the tip, I made mine as well. I thought you can only have one main GitHub pages page. How did you push yours? Is there a different way from pushing to the `gh-pages` branch? Only asking because I can't see the branch on your fork.

It's not all that bad self-hosting though. I get to learn all the ways it can mess up 😄

I managed to get a certificate for the original too, it's back up.

**Comment by NULLx76** [comment]
In settings you can specify which branch it should use and I just pointed it at master
![image](https://user-images.githubusercontent.com/1809198/93014512-f2d0ad00-f5b1-11ea-8bf5-74719807a310.png)

Self hosting can indeed be a lot of fun, lots of learning experiences to be had.

And as its back up again I'll close this issue.
